apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts
  namespace: carts
spec:
  template:
    spec:
      containers:
        - name: carts
          envFrom:
            - configMapRef:
                name: carts-ack
      serviceAccountName: carts-ack
#        image: 810918113647.dkr.ecr.us-west-2.amazonaws.com/carts:0.4.0-test
