apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: checkout
spec:
  template:
    spec:
      containers:
        - name: checkout
          envFrom:
            - configMapRef:
                name: checkout-v1
